POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTY1NjA3NTk0Mn0.y6Eqjvsa1w3_4hanadkbAOlZWf09UQWTvJyP9uzPPWk

{
  "author":"root",
  "url": "site.com",
  "title": "my blog two",
  "likes": 1,
  "year": 2022
}