POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3RAZ21haWwuY29tIiwiaWQiOjEsImlhdCI6MTY1NjIyNzI3MX0.KQSxMDf0tovDZhCdXz5aACti0XSJX4hmlfbDf-Y9dXo

{
  "author":"root",
  "url": "site.com",
  "title": "my blog eight",
  "likes": 1,
  "year": 2022
}