DELETE http://localhost:3001/api/blogs/7
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImthaWhhbGxAZ21haWwuY29tIiwiaWQiOjIsImlhdCI6MTY1NjI0MDIzOH0.UvL0_LbfhDvL2D0GouNYZWFqNDfm2QYGMbQneFlnnOk